//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class isch_Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public isch_Students()
        {
            this.isch_Absences = new HashSet<isch_Absences>();
        }
    
        public int st_id { get; set; }
        public int st_acc { get; set; }
        public string st_Name { get; set; }
        public string st_Specialization { get; set; }
        public string st_Nationality { get; set; }
        public string st_NationalId { get; set; }
        public string st_EnterTime { get; set; }
        public string st_PhoneNumber { get; set; }
        public string st_AcademyUser { get; set; }
        public Nullable<int> st_Schedule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Absences> isch_Absences { get; set; }
        public virtual isch_Schedules isch_Schedules { get; set; }
    }
}
