//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class isch_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public isch_Users()
        {
            this.isch_Excuses = new HashSet<isch_Excuses>();
            this.isch_NotiFication = new HashSet<isch_NotiFication>();
            this.isch_Subjects = new HashSet<isch_Subjects>();
        }
    
        public int u_id { get; set; }
        public string u_Name { get; set; }
        public string u_RealyName { get; set; }
        public string u_Pass { get; set; }
        public int u_Permission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Excuses> isch_Excuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_NotiFication> isch_NotiFication { get; set; }
        public virtual isch_Permissions isch_Permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Subjects> isch_Subjects { get; set; }
    }
}
