//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class isch_Permissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public isch_Permissions()
        {
            this.isch_Users = new HashSet<isch_Users>();
        }
    
        public int p_id { get; set; }
        public string p_Name { get; set; }
        public bool p_IsAdmin { get; set; }
        public bool p_IsTeacher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Users> isch_Users { get; set; }
    }
}
