//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class isch_Schedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public isch_Schedules()
        {
            this.isch_Students = new HashSet<isch_Students>();
        }
    
        public int s_id { get; set; }
        public Nullable<int> s_Subject1 { get; set; }
        public Nullable<int> s_Subject2 { get; set; }
        public Nullable<int> s_Subject3 { get; set; }
        public Nullable<int> s_Subject4 { get; set; }
        public Nullable<int> s_Subject5 { get; set; }
        public Nullable<int> s_Subject6 { get; set; }
        public Nullable<int> s_Subject7 { get; set; }
        public Nullable<int> s_Subject8 { get; set; }
    
        public virtual isch_Subjects isch_Subjects { get; set; }
        public virtual isch_Subjects isch_Subjects1 { get; set; }
        public virtual isch_Subjects isch_Subjects2 { get; set; }
        public virtual isch_Subjects isch_Subjects3 { get; set; }
        public virtual isch_Subjects isch_Subjects4 { get; set; }
        public virtual isch_Subjects isch_Subjects5 { get; set; }
        public virtual isch_Subjects isch_Subjects6 { get; set; }
        public virtual isch_Subjects isch_Subjects7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Students> isch_Students { get; set; }
    }
}
