//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class isch_Excuses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public isch_Excuses()
        {
            this.isch_Absences = new HashSet<isch_Absences>();
        }
    
        public int e_id { get; set; }
        public int e_User { get; set; }
        public string e_Text { get; set; }
        public System.DateTime e_EnterDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Absences> isch_Absences { get; set; }
        public virtual isch_Users isch_Users { get; set; }
    }
}
