//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISchoolData : DbContext
    {
        public ISchoolData()
            : base("name=ISchoolData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<isch_Absences> isch_Absences { get; set; }
        public virtual DbSet<isch_AbsenceTypes> isch_AbsenceTypes { get; set; }
        public virtual DbSet<isch_Excuses> isch_Excuses { get; set; }
        public virtual DbSet<isch_NotiFication> isch_NotiFication { get; set; }
        public virtual DbSet<isch_Permissions> isch_Permissions { get; set; }
        public virtual DbSet<isch_Schedules> isch_Schedules { get; set; }
        public virtual DbSet<isch_Students> isch_Students { get; set; }
        public virtual DbSet<isch_Subjects> isch_Subjects { get; set; }
        public virtual DbSet<isch_Users> isch_Users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
