//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class isch_Subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public isch_Subjects()
        {
            this.isch_Absences = new HashSet<isch_Absences>();
            this.isch_Schedules = new HashSet<isch_Schedules>();
            this.isch_Schedules1 = new HashSet<isch_Schedules>();
            this.isch_Schedules2 = new HashSet<isch_Schedules>();
            this.isch_Schedules3 = new HashSet<isch_Schedules>();
            this.isch_Schedules4 = new HashSet<isch_Schedules>();
            this.isch_Schedules5 = new HashSet<isch_Schedules>();
            this.isch_Schedules6 = new HashSet<isch_Schedules>();
            this.isch_Schedules7 = new HashSet<isch_Schedules>();
        }
    
        public int sub_id { get; set; }
        public int sub_Teacher { get; set; }
        public string sub_Type { get; set; }
        public string sub_Class { get; set; }
        public string sub_Place { get; set; }
        public string sub_Structure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Absences> isch_Absences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Schedules> isch_Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Schedules> isch_Schedules1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Schedules> isch_Schedules2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Schedules> isch_Schedules3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Schedules> isch_Schedules4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Schedules> isch_Schedules5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Schedules> isch_Schedules6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isch_Schedules> isch_Schedules7 { get; set; }
        public virtual isch_Users isch_Users { get; set; }
    }
}
