//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class isch_Absences
    {
        public int a_id { get; set; }
        public int a_Student { get; set; }
        public int a_Type { get; set; }
        public System.DateTime a_Date { get; set; }
        public Nullable<int> a_Excuse { get; set; }
        public int a_Subject { get; set; }
    
        public virtual isch_AbsenceTypes isch_AbsenceTypes { get; set; }
        public virtual isch_Excuses isch_Excuses { get; set; }
        public virtual isch_Students isch_Students { get; set; }
        public virtual isch_Subjects isch_Subjects { get; set; }
    }
}
